package com.yuesnm.pukka.client.cxf.respbtos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2018-01-24T17:09:57.444+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "BtosResponse", 
                  wsdlLocation = "http://api.yuesnm.com:83/input-pukka/BtosResp?wsdl",
                  targetNamespace = "respBtos") 
public class BtosResponse extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("respBtos", "BtosResponse");
    public final static QName Btos = new QName("respBtos", "Btos");
    static {
        URL url = null;
        try {
            url = new URL("http://api.yuesnm.com:83/input-pukka/BtosResp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BtosResponse.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://api.yuesnm.com:83/input-pukka/BtosResp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BtosResponse(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BtosResponse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BtosResponse() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BtosResponse(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BtosResponse(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BtosResponse(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IInputPukkaService
     */
    @WebEndpoint(name = "Btos")
    public IInputPukkaService getBtos() {
        return super.getPort(Btos, IInputPukkaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IInputPukkaService
     */
    @WebEndpoint(name = "Btos")
    public IInputPukkaService getBtos(WebServiceFeature... features) {
        return super.getPort(Btos, IInputPukkaService.class, features);
    }

}
